version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine
    container_name: syncsphere-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: syncsphere
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      # Persistent data storage
      - postgres_data:/var/lib/postgresql/data
      # Initialize database with schema
      - ./backend/scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql:ro
      # Custom PostgreSQL configuration
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    networks:
      - syncsphere-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d syncsphere"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis Cache Service (optional, for complete development environment)
  redis:
    image: redis:7-alpine
    container_name: syncsphere-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/etc/redis/redis.conf:ro
    networks:
      - syncsphere-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: redis-server /etc/redis/redis.conf

  # pgAdmin (optional, for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: syncsphere-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@syncsphere.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - syncsphere-network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - admin

volumes:
  postgres_data:
    driver: local
    name: syncsphere_postgres_data
  redis_data:
    driver: local
    name: syncsphere_redis_data
  pgadmin_data:
    driver: local
    name: syncsphere_pgadmin_data

networks:
  syncsphere-network:
    driver: bridge
    name: syncsphere-network