version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: syncsphere-postgres-test
    environment:
      POSTGRES_DB: syncsphere_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256 --auth-local=scram-sha-256'
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - test-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d syncsphere_test']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis-test:
    image: redis:7-alpine
    container_name: syncsphere-redis-test
    ports:
      - '6380:6379'
    volumes:
      - redis_test_data:/data
    networks:
      - test-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    command: redis-server --appendonly yes --requirepass test_password

volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local

networks:
  test-network:
    driver: bridge
